repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@^3.1.0
                - '@trivago/prettier-plugin-sort-imports@^4.3.0'
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.55.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@^8.55.0
                - '@typescript-eslint/eslint-plugin@^6.13.2'
                - '@typescript-eslint/parser@^6.13.2'
