repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            additional_dependencies:
                - '@trivago/prettier-plugin-sort-imports@^5.0.0'
                - prettier@^3.4.2
                - prettier-plugin-sort-json@^4.1.1

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v9.33.0
      hooks:
          - id: eslint
            types: [file]
            types_or: [javascript, jsx, ts, tsx]
            additional_dependencies:
                - eslint@^9.15.0
                - eslint-import-resolver-typescript@^3.6.3
                - eslint-plugin-import@^2.31.0
                - typescript-eslint@^8.16.0
