name: pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Sanitize repository slug
              uses: actions/github-script@v7
              id: repository_slug
              with:
                  result-encoding: string
                  script: return '${{ github.repository }}'.toLowerCase()
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: ghcr.io/${{ steps.repository_slug.outputs.result }}:${{ github.sha }}

    publish:
        needs: build
        runs-on: ubuntu-latest
        if: ${{ github.ref == 'refs/heads/main' }}
        steps:
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Tag Docker image with branch name
              run: |
                  DOCKER_IMAGE=ghcr.io/${{ github.repository }}
                  DOCKER_IMAGE=${DOCKER_IMAGE,,}
                  TAG=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
                  docker pull $DOCKER_IMAGE:$GITHUB_SHA
                  docker tag $DOCKER_IMAGE:$GITHUB_SHA $DOCKER_IMAGE:$TAG
                  docker push $DOCKER_IMAGE:$TAG
